-- =========================================================
-- 0. DROP DAS TABELAS (ordem inversa por causa das FKs)
-- =========================================================

DROP TABLE IF EXISTS Conversa     CASCADE;
DROP TABLE IF EXISTS Posts        CASCADE;
DROP TABLE IF EXISTS Prestador    CASCADE;
DROP TABLE IF EXISTS Area_Atuacao CASCADE;
DROP TABLE IF EXISTS Tipo         CASCADE;
DROP TABLE IF EXISTS Usuario      CASCADE;


-- =========================================================
-- 1. CRIAÇÃO DAS TABELAS (SEM CHAVES)
-- =========================================================

CREATE TABLE Usuario (
    IdUsuario   INT			 not NULL,
    Email       VARCHAR(255) NOT NULL,
    Senha       VARCHAR(255) NOT NULL,
    Nome        VARCHAR(255) NOT NULL,
    TipoUsuario VARCHAR(50),
    Telefone    VARCHAR(20),
    foto        VARCHAR(255),
    Local       VARCHAR(255)
);

CREATE TABLE Area_Atuacao (
    IdArea INT          NOT NULL,
    Area   VARCHAR(255) NOT NULL
);

CREATE TABLE Tipo (
    IdTipo INT          NOT NULL,
    Tipo   VARCHAR(255) NOT NULL
);

CREATE TABLE Prestador (
    IdPrestador INT  NOT NULL,
    Id_Usuario  INT  NOT NULL,
    Descricao   TEXT,
    AreaAtuacao INT,
    Categoria   INT
);

CREATE TABLE Posts (
    IdPost      INT          NOT NULL,
    IdPrestador INT          NOT NULL,
    titulo      VARCHAR(255) NOT NULL,
    Legenda     TEXT,
    DataEnvio   TIMESTAMP
);

CREATE TABLE Conversa (
    IdPrestador INT       NOT NULL,
    IdUsuario   INT       NOT NULL,
    Mensagem    TEXT      NOT NULL,
    DataEnvio   TIMESTAMP NOT NULL
);


-- =========================================================
-- 2. DEFINIÇÃO DAS CHAVES PRIMÁRIAS (PK)
-- =========================================================

ALTER TABLE Usuario
    ADD CONSTRAINT PK_Usuario PRIMARY KEY (IdUsuario);

ALTER TABLE Area_Atuacao
    ADD CONSTRAINT PK_Area_Atuacao PRIMARY KEY (IdArea);

ALTER TABLE Tipo
    ADD CONSTRAINT PK_Tipo PRIMARY KEY (IdTipo);

ALTER TABLE Prestador
    ADD CONSTRAINT PK_Prestador PRIMARY KEY (IdPrestador);

ALTER TABLE Posts
    ADD CONSTRAINT PK_Posts PRIMARY KEY (IdPost);

-- Chave primária composta para a tabela de relacionamento N:N (Conversa)
ALTER TABLE Conversa
    ADD CONSTRAINT PK_Conversa PRIMARY KEY (IdPrestador, IdUsuario);


-- =========================================================
-- 3. DEFINIÇÃO DAS CHAVES ESTRANGEIRAS (FK)
-- =========================================================

-- Chaves Estrangeiras de Prestador
ALTER TABLE Prestador
    ADD CONSTRAINT FK_Prestador_Usuario
        FOREIGN KEY (Id_Usuario)  REFERENCES Usuario(IdUsuario),
    ADD CONSTRAINT FK_Prestador_Area
        FOREIGN KEY (AreaAtuacao) REFERENCES Area_Atuacao(IdArea),
    ADD CONSTRAINT FK_Prestador_Tipo
        FOREIGN KEY (Categoria)   REFERENCES Tipo(IdTipo);

-- Chaves Estrangeiras de Posts
ALTER TABLE Posts
    ADD CONSTRAINT FK_Posts_Prestador
        FOREIGN KEY (IdPrestador) REFERENCES Prestador(IdPrestador);

-- Chaves Estrangeiras de Conversa
ALTER TABLE Conversa
    ADD CONSTRAINT FK_Conversa_Prestador
        FOREIGN KEY (IdPrestador) REFERENCES Prestador(IdPrestador),
    ADD CONSTRAINT FK_Conversa_Usuario
        FOREIGN KEY (IdUsuario)   REFERENCES Usuario(IdUsuario);

-- Auto incremento de id
ALTER TABLE usuario 
ALTER COLUMN idUsuario ADD GENERATED BY DEFAULT AS IDENTITY;


-- =========================================================
-- 4. INSERTS: Area_Atuacao (20 registros)
-- =========================================================

INSERT INTO Area_Atuacao (IdArea, Area) VALUES
    (1,  'Tecnologia da Informação'),
    (2,  'Construção Civil'),
    (3,  'Saúde e Bem-estar'),
    (4,  'Educação e Ensino'),
    (5,  'Design e Criatividade'),
    (6,  'Jurídico e Contabilidade'),
    (7,  'Beleza e Estética'),
    (8,  'Manutenção e Reparos'),
    (9,  'Gastronomia e Alimentação'),
    (10, 'Transporte e Logística'),
    (11, 'Marketing e Publicidade'),
    (12, 'Fotografia e Audiovisual'),
    (13, 'Arquitetura e Urbanismo'),
    (14, 'Engenharia Elétrica'),
    (15, 'Engenharia Mecânica'),
    (16, 'Eventos e Entretenimento'),
    (17, 'Segurança e Vigilância'),
    (18, 'Limpeza e Conservação'),
    (19, 'Meio Ambiente e Sustentabilidade'),
    (20, 'Recursos Humanos e Consultoria');


-- =========================================================
-- 5. INSERTS: Tipo (20 registros)
-- =========================================================

INSERT INTO Tipo (IdTipo, Tipo) VALUES
    (1,  'Freelancer'),
    (2,  'Autônomo'),
    (3,  'Empresa'),
    (4,  'MEI'),
    (5,  'Cooperativa'),
    (6,  'Estagiário'),
    (7,  'Consultor'),
    (8,  'Terceirizado'),
    (9,  'Prestador Eventual'),
    (10, 'Prestador Recorrente'),
    (11, 'Microempresa'),
    (12, 'Startup'),
    (13, 'ONG'),
    (14, 'Profissional Liberal'),
    (15, 'Técnico Especializado'),
    (16, 'Artesão'),
    (17, 'Agência'),
    (18, 'Associação'),
    (19, 'Representante Comercial'),
    (20, 'Sociedade Simples');