-- =========================================================
-- 0. DROP DAS TABELAS (ordem inversa por causa das FKs)
-- =========================================================

DROP TABLE IF EXISTS Conversa     CASCADE;
DROP TABLE IF EXISTS Posts        CASCADE;
DROP TABLE IF EXISTS Prestador    CASCADE;
DROP TABLE IF EXISTS Area_Atuacao CASCADE;
DROP TABLE IF EXISTS Tipo         CASCADE;
DROP TABLE IF EXISTS Usuario      CASCADE;


-- =========================================================
-- 1. CRIAÇÃO DAS TABELAS
-- =========================================================

CREATE TABLE Usuario (
    IdUsuario   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email       VARCHAR(255) NOT NULL UNIQUE,
    Senha       VARCHAR(255) NOT NULL,
    Nome        VARCHAR(255) NOT NULL,
    TipoUsuario VARCHAR(50),
    Telefone    VARCHAR(20),
    foto        VARCHAR(255),
    Local       VARCHAR(255)
);

CREATE TABLE Area_Atuacao (
    IdArea INT          NOT NULL,
    Area   VARCHAR(255) NOT NULL,
    CONSTRAINT PK_Area_Atuacao PRIMARY KEY (IdArea)
);

CREATE TABLE Tipo (
    IdTipo INT          NOT NULL,
    Tipo   VARCHAR(255) NOT NULL,
    CONSTRAINT PK_Tipo PRIMARY KEY (IdTipo)
);

CREATE TABLE Prestador (
    IdPrestador INT GENERATED BY DEFAULT AS IDENTITY,
    Id_Usuario  INT  NOT NULL,
    Descricao   TEXT,
    AreaAtuacao INT,
    Categoria   INT,
    CONSTRAINT PK_Prestador PRIMARY KEY (IdPrestador)
);

CREATE TABLE Posts (
    IdPost      INT GENERATED BY DEFAULT AS IDENTITY,
    IdPrestador INT          NOT NULL,
    titulo      VARCHAR(255) NOT NULL,
    Legenda     TEXT,
    DataEnvio   TIMESTAMP,
    CONSTRAINT PK_Posts PRIMARY KEY (IdPost)
);

CREATE TABLE Conversa (
    IdPrestador INT       NOT NULL,
    IdUsuario   INT       NOT NULL,
    Mensagem    TEXT      NOT NULL,
    DataEnvio   TIMESTAMP NOT NULL,
    CONSTRAINT PK_Conversa PRIMARY KEY (IdPrestador, IdUsuario)
);


-- =========================================================
-- 2. CHAVES ESTRANGEIRAS (FK)
-- =========================================================

-- Prestador → Usuario, Area_Atuacao, Tipo
ALTER TABLE Prestador
    ADD CONSTRAINT FK_Prestador_Usuario
        FOREIGN KEY (Id_Usuario)  REFERENCES Usuario(IdUsuario),
    ADD CONSTRAINT FK_Prestador_Area
        FOREIGN KEY (AreaAtuacao) REFERENCES Area_Atuacao(IdArea),
    ADD CONSTRAINT FK_Prestador_Tipo
        FOREIGN KEY (Categoria)   REFERENCES Tipo(IdTipo);

-- Posts → Prestador
ALTER TABLE Posts
    ADD CONSTRAINT FK_Posts_Prestador
        FOREIGN KEY (IdPrestador) REFERENCES Prestador(IdPrestador);

-- Conversa → Prestador, Usuario
ALTER TABLE Conversa
    ADD CONSTRAINT FK_Conversa_Prestador
        FOREIGN KEY (IdPrestador) REFERENCES Prestador(IdPrestador),
    ADD CONSTRAINT FK_Conversa_Usuario
        FOREIGN KEY (IdUsuario)   REFERENCES Usuario(IdUsuario);


-- =========================================================
-- 3. INSERTS: Area_Atuacao (20 registros)
-- =========================================================

INSERT INTO Area_Atuacao (IdArea, Area) VALUES
    (1,  'Tecnologia da Informação'),
    (2,  'Construção Civil'),
    (3,  'Saúde e Bem-estar'),
    (4,  'Educação e Ensino'),
    (5,  'Design e Criatividade'),
    (6,  'Jurídico e Contabilidade'),
    (7,  'Beleza e Estética'),
    (8,  'Manutenção e Reparos'),
    (9,  'Gastronomia e Alimentação'),
    (10, 'Transporte e Logística'),
    (11, 'Marketing e Publicidade'),
    (12, 'Fotografia e Audiovisual'),
    (13, 'Arquitetura e Urbanismo'),
    (14, 'Engenharia Elétrica'),
    (15, 'Engenharia Mecânica'),
    (16, 'Eventos e Entretenimento'),
    (17, 'Segurança e Vigilância'),
    (18, 'Limpeza e Conservação'),
    (19, 'Meio Ambiente e Sustentabilidade'),
    (20, 'Recursos Humanos e Consultoria');


-- =========================================================
-- 4. INSERTS: Tipo (20 registros)
-- =========================================================

INSERT INTO Tipo (IdTipo, Tipo) VALUES
    (1,  'Freelancer'),
    (2,  'Autônomo'),
    (3,  'Empresa'),
    (4,  'MEI'),
    (5,  'Cooperativa'),
    (6,  'Estagiário'),
    (7,  'Consultor'),
    (8,  'Terceirizado'),
    (9,  'Prestador Eventual'),
    (10, 'Prestador Recorrente'),
    (11, 'Microempresa'),
    (12, 'Startup'),
    (13, 'ONG'),
    (14, 'Profissional Liberal'),
    (15, 'Técnico Especializado'),
    (16, 'Artesão'),
    (17, 'Agência'),
    (18, 'Associação'),
    (19, 'Representante Comercial'),
    (20, 'Sociedade Simples');
